version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: DockerFile
    container_name: sellGoldServer
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER:
      DB_PASSWORD:
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: "5432"
    networks:
      - sellGoldNetwork
    restart: on-failure
    command: sh -c "sleep 10 && ./server"
  db:
    image: postgres:13
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      - sellGoldNetwork

networks:
  sellGoldNetwork:
