version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: DockerFile
    container_name: sellGoldServer
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER:
      DB_PASSWORD:
      DB_NAME: postgres
      DB_HOST:
      DB_PORT: "5432"
  db:
    image: postgres:13
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
