version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: DockerFile
    container_name: sellGoldServer
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: 663857
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"